### ISSUE TITLE
error: use of undeclared identifier       'get_current_dir_name'

### ISSUE THREAD

**Issue by chaochaowong** [lxwgcool/CircMarker#4]
Hi, I've tried to `sudo make` circMaker on Macs and got this error. Do you have any hints I can bypass it?
```
g++ -O3 -Wall  -c ../CircRnaDetectDraft/main.cpp
../CircRnaDetectDraft/main.cpp:276:43: error: use of undeclared identifier
      'get_current_dir_name'
    string strCmd = (string)"mkdir -p " + get_current_dir_name() + "/Det...
                                          ^
1 error generated.
make: *** [main.o] Error 1
```
Sincerely,
CJ

**Comment by lxwgcool** [comment]
Thank you so much for using CircMarker. May I know your gcc version? CircMarker requires C++11. Therefore, please use gcc v5.4.0 or above. Please let me know if you can compile it successfully.

**Comment by lxwgcool** [comment]
One more question: may I know which OS were you using? This makefile is for Linux only. You may get error if you use it in MacOS.
Thanks

**Comment by lxwgcool** [comment]
> Hi, I've tried to `sudo make` circMaker on Macs and got this error. Do you have any hints I can bypass it?
> 
> ```
> g++ -O3 -Wall  -c ../CircRnaDetectDraft/main.cpp
> ../CircRnaDetectDraft/main.cpp:276:43: error: use of undeclared identifier
>       'get_current_dir_name'
>     string strCmd = (string)"mkdir -p " + get_current_dir_name() + "/Det...
>                                           ^
> 1 error generated.
> make: *** [main.o] Error 1
> ```
> 
> Sincerely,
> CJ

Thank you so much for using circmarker. Please check my comments in this ticket.

**Comment by chaochaowong** [comment]
Got it. Thank you, @lxwgcool . I was using MacOS 10.15.13 and got the above error. I've switched to Ubuntu (18) with gcc v7.5, and it works.
